arsenal_players = [
    "ramsdale",
    "raya",
    "hein",
    "saliba",
    "white",
    "gabriel",
    "timber",
    "kiwior",
    "soares",
    "tomiyasu",
    "zinchenko",
    "partey",
    "ødegaard",
    "smith rowe",
    "jorginho",
    "vieira",
    "elneny",
    "havertz",
    "rice",
    "saka",
    "jesus",
    "martinelli",
    "nketiah",
    "trossard",
    "nelson",
]